import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function BlogLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>{children}</div>
  );
}
