import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Futures",
  description: "Generated by create next app",
};

export default function FuturesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>{children}</main>
  );
}
